### ISSUE TITLE
I want add Dir-size column forever

### ISSUE THREAD

**Issue by redhed100** [brows-app/brows#6]
**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version latest

**Additional context**
I want add Dir-size column forever!
How can i do it?
I tried go to customize, but i couldn't.
dir-size is adjusted for each folder, and only in them shows dir-size, and I want it to show everywhere, and if not needed, you can disable it everywhere.

**Comment by kyourek** [comment]
Type the `config` command to get to the root of configuration files.

![cmd](https://github.com/user-attachments/assets/e2e8cb09-945e-43f5-9cd7-c4763b51e2d6)

Make sure you have a file called *filesystem.conf* in that directory. If you don't, copy *filesystem.conf.default* from the *default* directory and rename it to *filesystem.conf* in the current directory.

![conf](https://github.com/user-attachments/assets/f295736e-2353-4e75-ac1a-528198f8ef1c)

Edit *filesystem.conf* in a text editor and add this line:
```
DefaultKey = Name|Length|LastWriteTime|Extension|DirectorySize
```

You should now have an additional column with directory sizes in file-system panels. Let me know if that works for you.

**Comment by redhed100** [comment]
Thanks!

**Comment by redhed100** [comment]
Thanks!
